// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	// Avatar User avatar
	Avatar *string `json:"avatar,omitempty"`

	// Id User ID
	Id int64 `json:"id"`

	// Name User name
	Name string `json:"name"`

	// Nickname User nickname
	Nickname *string `json:"nickname,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Callback from Auth0
	// (GET /callback)
	Callback(c *fiber.Ctx) error
	// Logs user into the system via Auth0
	// (GET /login)
	Login(c *fiber.Ctx) error
	// Logs out current logged in user session
	// (GET /logout)
	Logout(c *fiber.Ctx) error
	// Get user information
	// (GET /user)
	GetUser(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// Callback operation middleware
func (siw *ServerInterfaceWrapper) Callback(c *fiber.Ctx) error {

	return siw.Handler.Callback(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *fiber.Ctx) error {

	return siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *fiber.Ctx) error {

	return siw.Handler.Logout(c)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *fiber.Ctx) error {

	return siw.Handler.GetUser(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/callback", wrapper.Callback)

	router.Get(options.BaseURL+"/login", wrapper.Login)

	router.Get(options.BaseURL+"/logout", wrapper.Logout)

	router.Get(options.BaseURL+"/user", wrapper.GetUser)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUTU/cPBD+K9a87zGNw1JVyDdEEVq0qpBaToiD68wmLo7t2uNFCOW/V3Y2lC679NLD",
	"nmLnmY/n8Xw8g3KDdxYtRRDPEFWPgyzHyxBcyAcfnMdAGstv5VrM3xajCtqTdhbEZMwKVsHahUESCNCW",
	"ThdQAT15nK7YYYCxggFjlN3BQDP84hopaNvBOFYQ8GfSAVsQd7BNOJvfjxXcRtzDWm4kyfA2XbZmW/BN",
	"sgp0e8Bl+XlH56ePe3VaOeCBEAXak9Nq9fCe2wz/7W10C9v892PGtF27tzG/9ToyHRn1yK4TXid2frOE",
	"CoxWaGMhMZGBcy9Vj2xRN1BBCgYE9EQ+Cs4fHx9rWeDahY5vfSNfLS8uv3y9/LCom7qnwWR5pMnkcK+T",
	"bTDEic5J3dRNNnMerfQaBJyWXxV4SX2pJVfSmO9SPeRLh5Q/udYyS1q2IOBiNsgvEr3LZCbpa5kMTW1s",
	"CW05Su+NVsWb/4iZxjwH+fR/wDUI+I//HhS+nRI+jUh53X1dPOcupYlpGGR4esWOrYMb2HmivikW3LhO",
	"24OiVgU9SkUr10WWcndqS670UnyKhAPbaLmj0CV6T2KGj1ejS8RUCgEtMeO6Dlum7aQ8Yiw9XHSm7RLa",
	"q/IKqSypHZmLpvlnEkv8PQpvpxpNi6uwrY7kea+Q5g56xa7YYMj7AcTd7u5aOSUNm/A/dpLg3GSsd5HE",
	"WXPWcOk135zAWO3GuAmuTSpfdgO9+NyPvwIAAP//YERhaiYHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
